namespace CrescentSchool.Models.Enums;

public enum TajweedRules
{
    NoonAndMeemMushaddad = 1,
    Qalqala = 2,
    IzharHalqi = 3,
    IdghamWithoutGunnah = 4,
    IdghamWithGunnah = 5,
    Iqlab = 6,
    IkhfaaHaqiqi = 7,
    IdghamSagheer = 8,
    BilabialIkhfaa = 9,
    BilabialIzhar = 10,
    AttachedMadd = 11,
    DetachedMadd = 12,
    TemporaryMaddDueToSukoon = 13,
    CompulsoryMaddHeavy = 14,
    CompulsoryMaddLight = 15,
    ConnectingMaddLesser = 16,
    ConnectingMaddGreater = 17,
    SeparateLetters = 18,
    SoftMadd = 19,
    AlifMaddRule = 20,
    HeavinessAndLightness = 21,
    RuleOfLaamInAllah = 22,
    RulesOfRa = 23,
    RulesOfLaamSakinah = 24,
    HamzatulWasl = 25,
    HamzatulQat = 26,
    MeetingTwoLettersWithSukoon = 27,
    RulesOfMeetingTwoLetters = 28,
    ArticulationPoints = 29,
    CharacteristicsOfLetters = 30,
    StoppingAndStarting = 31
}